nicopaleis/blueprints/booklet.py
from string import Template

from markdown import markdown
from flask import (
    Blueprint,
    render_template,
    request,
    make_response,
    jsonify,
)

from nicopaleis.db import get_db
from nicopaleis.entries import fetch_data, put_data, split


bp = Blueprint('booklet', __name__, url_prefix='/nicopaleis/booklet')


def prime(string, parameters):
    "Return string where all `parameters` have been substituted in `string`."

    template = Template(string)
    return template.safe_substitute(parameters)


def taggify(tag, value):
    "Return <`tag`>`value`</`tag`>."

    if value == '':
        return ''
    tag = tag.upper()
    return f"<{tag}>{value}</{tag}>"


def prep_snippets(snip, param):
    """Split snippets `snip` into separate languages
    and substitute parameters `param` with their values."""

    snip = split(snip)
    snip['nl'] = {k:prime(v, param['nl']) for k,v in snip['nl'].items()}
    snip['en'] = {k:prime(v, param['en']) for k,v in snip['en'].items()}
    return snip


def build_html(selection, messages, title):
    "Return all selected messages as xml."
    title = title.split('.')[0]
    messages = [msg for msg in messages if msg['mededeling'] in selection]
    return render_template('booklet.html', book_title=title, messages=messages)


@bp.route('/', methods=('GET', 'POST'))
def manage():
    parameters = split(fetch_data('parameters', ['value_nl', 'value_en']))
    snippets = fetch_data('snippets', ['value_nl', 'value_en'])
    snippets = prep_snippets(snippets, parameters)
    variables = {k:{**parameters[k], **snippets[k]} for k in parameters}

    sql = """
        SELECT
            m.label            as mededeling,
            subject_nl         as koptekst,
            subject_en         as koptekst_en,
            body_nl            as inhoud,
            body_en            as inhoud_en,
            value              as layout,
            faculteit,
            communicatiekanaal,
            type_mededeling,
            muteerbaar,
            actueel,
            formaat,
            e_mail_adres_1,
            antwoordadres,
            ander_antwoordadres,
            verstuur_in_context,
            verstuur_vanaf_tijdstip,
            zichtbaar_in_student,
            documentset,
            keuze_zichtbaar_in_document,
            toon_antwoordadres_no_reply,
            toon_antwoordadres_mijzelf,
            toon_antwoordadres_opgeven
        FROM
            messages m
        INNER JOIN
            settings s
            ON m.settings = s.label
        INNER JOIN
            layouts l
            ON m.layout = l.label;
    """

    db = get_db()
    messages = [dict(row) for row in db.execute(sql).fetchall()]

    for msg in messages:
        layout_nl = prime(msg['layout'], variables['nl'])
        layout_en = prime(msg['layout'], variables['en'])

        msg['mededeling'] = msg['mededeling'].upper()

        msg['koptekst'] = prime(msg['koptekst'], variables['nl'])
        msg['koptekst_en'] = prime(msg['koptekst_en'], variables['en'])
        msg['koptekst_nls'] = msg['koptekst']

        msg['inhoud'] = markdown(prime(msg['inhoud'], variables['nl']))
        msg['inhoud_en'] = markdown(prime(msg['inhoud_en'], variables['en']))

        msg['inhoud'] = prime(layout_nl, dict(content=msg['inhoud']))
        msg['inhoud_en'] = prime(layout_en, dict(content=msg['inhoud_en']))
        msg['inhoud_nls'] = msg['inhoud']

        msg['omschrijving'] = msg['koptekst']
        msg['omschrijving_en'] = msg['koptekst_en']
        msg['omschrijving_nls'] = msg['koptekst']

        del msg['layout']

    if request.method == 'POST':
        r = request.get_json()
        selection = r['selection']
        filename = r['filename']
        booklet = build_html(selection, messages, filename)
        return make_response(jsonify(booklet))
    return render_template(
        'manager/export.html',
        module='booklet',
        extension='html',
        mime='text/html',
        data = [msg['mededeling'] for msg in messages]
    )

nicopaleis/blueprints/xml.py
from string import Template

from markdown import markdown
from flask import (
    Blueprint,
    render_template,
    request,
    make_response,
    jsonify,
)

from nicopaleis.db import get_db
from nicopaleis.entries import fetch_data, put_data, split


bp = Blueprint('xml', __name__, url_prefix='/nicopaleis/xml')


def prime(string, parameters):
    "Return string where all `parameters` have been substituted in `string`."

    template = Template(string)
    return template.safe_substitute(parameters)


def fix(string):
    "Convert special characters to entity references within xml tags."

    replacements = {
        '<br>': '<br />',
        '<hr>': '<hr />',
        '&':    '&amp;',
        '<':    '&lt;',
        '>':    '&gt;',
        '"':    '&quot;',
        "'":    '&apos;',
    }
    for replacement in replacements.items():
        string = string.replace(*replacement)
    return string


def taggify(tag, value):
    "Return <`tag`>`value`</`tag`>."

    if value == '':
        return ''
    tag = tag.upper()
    return f"<{tag}>{value}</{tag}>"


def prep_snippets(snip, param):
    """Split snippets `snip` into separate languages
    and substitute parameters `param` with their values."""

    snip = split(snip)
    snip['nl'] = {k:prime(v, param['nl']) for k,v in snip['nl'].items()}
    snip['en'] = {k:prime(v, param['en']) for k,v in snip['en'].items()}
    return snip


def build_xml(selection, messages):
    "Return all selected messages as xml."

    content = []
    for message in messages:
        if not message['mededeling'] in selection:
            continue
        row = '\n'.join([taggify(k, v) for k,v in message.items() if v != ''])
        content.append(f"<OSU_MEDEDELING_ROW>\n{row}</OSU_MEDEDELING_ROW>\n")
    content = [item for item in content if item != '']
    content = '\n'.join(content)
    return (
        '<?xml version="1.0"?>\n'
        '<ROWSET>\n'
        '<ROW>\n'
        '     <OSU_MEDEDELING>\n'
        f'{content}\n'
        '     </OSU_MEDEDELING>\n'
        '</ROW>\n'
        '</ROWSET>\n'
    )


@bp.route('/', methods=('GET', 'POST'))
def manage():
    parameters = split(fetch_data('parameters', ['value_nl', 'value_en']))
    snippets = fetch_data('snippets', ['value_nl', 'value_en'])
    snippets = prep_snippets(snippets, parameters)
    variables = {k:{**parameters[k], **snippets[k]} for k in parameters}

    sql = """
        SELECT
            m.label            as mededeling,
            subject_nl         as koptekst,
            subject_en         as koptekst_en,
            body_nl            as inhoud,
            body_en            as inhoud_en,
            value              as layout,
            faculteit,
            communicatiekanaal,
            type_mededeling,
            muteerbaar,
            actueel,
            formaat,
            e_mail_adres_1,
            antwoordadres,
            ander_antwoordadres,
            verstuur_in_context,
            verstuur_vanaf_tijdstip,
            zichtbaar_in_student,
            documentset,
            keuze_zichtbaar_in_document,
            toon_antwoordadres_no_reply,
            toon_antwoordadres_mijzelf,
            toon_antwoordadres_opgeven
        FROM
            messages m
        INNER JOIN
            settings s
            ON m.settings = s.label
        INNER JOIN
            layouts l
            ON m.layout = l.label;
    """

    db = get_db()
    messages = [dict(row) for row in db.execute(sql).fetchall()]

    for msg in messages:
        layout_nl = prime(msg['layout'], variables['nl'])
        layout_en = prime(msg['layout'], variables['en'])

        msg['koptekst'] = prime(msg['koptekst'], variables['nl'])
        msg['koptekst_en'] = prime(msg['koptekst_en'], variables['en'])
        msg['koptekst_nls'] = msg['koptekst']

        msg['inhoud'] = markdown(prime(msg['inhoud'], variables['nl']))
        msg['inhoud_en'] = markdown(prime(msg['inhoud_en'], variables['en']))

        msg['inhoud'] = fix(prime(layout_nl, dict(content=msg['inhoud'])))
        msg['inhoud_en'] = fix(prime(layout_en, dict(content=msg['inhoud_en'])))
        msg['inhoud_nls'] = msg['inhoud']

        msg['omschrijving'] = msg['koptekst']
        msg['omschrijving_en'] = msg['koptekst_en']
        msg['omschrijving_nls'] = msg['koptekst']

        del msg['layout']

    if request.method == 'POST':
        selection = request.get_json()
        xml = build_xml(selection, messages)
        return make_response(jsonify(xml))
    return render_template(
        'manager/xml.html',
        module='xml',
        data = [msg['mededeling'] for msg in messages]
    )

nicopaleis/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - Nicopaleis</title>
    <!-- styling -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <!-- favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>
<body>
    <header>
        <div class="banner">
            <a class="logo" href="{{ url_for('home') }}">
                <img src="{{ url_for('static', filename='paleis.svg') }}" alt="Nicopaleis">
                <div class="logo--name">Nicopaleis</div>
            </a>
            <nav class="monospace">
                <a href="{{ url_for('parameters.manage') }}">parameters</a>
                <a href="{{ url_for('snippets.manage') }}">snippets</a>
                <a href="{{ url_for('layouts.manage') }}">layouts</a>
                <a href="{{ url_for('settings.manage') }}">settings</a>
                <a href="{{ url_for('messages.manage') }}">messages</a>
                <a href="{{ url_for('xml.manage') }}">xml</a>
                <a href="{{ url_for('booklet.manage') }}">booklet</a>
                <a href="javascript:shutDown()">[x]</a>
            </nav>
        </div>
        <div id="flash" class="flash monospace">
        {% for message in get_flashed_messages() %}
            <div class="monospace">{{ message }}</div>
        {% endfor %}
        </div>
        {% block page %}{% endblock%}
    </header>
    <main>
        {% block content %}{% endblock%}
    </main>
    <footer>
        <div class="monospace">
            <a href="https://github.com/uu-asc/nicopaleis-email-templates">e-mail template generator</a>
        </div>
        <div class="monospace">
            {{ version }}
        </div>
        <div class="monospace">
            <a href="mailto:l.c.vriend@uu.nl">l.c.vriend@uu.nl</a>
        </div>
    </footer>
<script>
    const flash = document.getElementById('flash');

    // FLASH
    function displayFlash (text) {
        flash.innerText = text;
        setTimeout(() => flash.innerText = '', 2500);
    }

    function shutDown() {
        fetch('/shutdown')
            .then((response) => {
                displayFlash('application has shut down---you may close this tab')
            });
        };
</script>
{% block script %}{% endblock %}
<script src="{{ url_for('static', filename='scripts/collapsibles.js') }}"></script>
</body>
</html>

nicopaleis/templates/booklet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ book_title }}</title>
    <style>
        body {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        body > * {
            font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif
        }
        nav > ol > li > ul {
            padding-left: 1em;
        }
        nav a {
            padding: 0.25em;
            text-decoration: none;
            color: black;
        }
        nav a:hover {
            background-color: lightblue;
        }
        nav ol {
            counter-reset: item;
        }
        nav li {
            display: block;
        }
        nav li:before {
            content: counters(item, ".") " ";
            counter-increment: item;
        }
    </style>
</head>

<body>
    <h1>{{ book_title }}</h1>
    <h2 id="#inhoudsopgave">Inhoudsopgave</h2>
    <nav>
        <ol>
            {% for msg in messages %}
            <li>
                <a href="#{{ msg['mededeling'] }}">{{ msg['mededeling'] }}</a>
                <ol>
                    <li>
                        <a href="#{{ msg['mededeling'] }}_nl">{{ msg['koptekst'] }}</a>
                    </li>
                    <li>
                        <a href="#{{ msg['mededeling'] }}_en">{{ msg['koptekst_en'] }}</a>
                    </li>
                </ol>
            </li>
            {% endfor %}
        </ol>
    </nav>

    <h2>Berichten</h2>
    {% for msg in messages %}
    <h3 id="{{ msg['mededeling'] }}">{{ msg['mededeling'] }}</h3>
    <h4 id="{{ msg['mededeling'] }}_nl">{{ msg['koptekst'] }}</h4>
    <div>{{ msg['inhoud']|safe }}</div>
    <h4 id="{{ msg['mededeling'] }}_en">{{ msg['koptekst_en'] }}</h4>
    <div>{{ msg['inhoud_en']|safe }}</div>
    <hr>
    {% endfor %}
</body>
</html>

nicopaleis/templates/home.html
{% extends 'base.html' %}

{% block page %}
<div class="page">
    <h2>{% block title %}Home{% endblock %}</h2>
</div>
{% endblock page %}

{% block content %}
<div class="info">
    <h3>Inleiding</h3>
    <p>
        Met deze applicatie kun je e-mailberichten beheren en daar vervolgens in huisstijl opgemaakte html van genereren. De grondgedachten zijn:
    </p>
    <p>
        <ul>
            <li>Scheiding van inhoud en opmaak.</li>
            <li>Geparametriseerde teksten.</li>
            <li>Modulaire opbouw via blokteksten.</li>
            <li>Consistente opmaak van berichten.</li>
        </ul>
    </p>
    <p>
        De applicatie maakt gebruik van <i>markdown:</i> een opmaaktaal voor platte tekst. Markdown kan eenvoudig worden omgezet naar html. Zie <a href="https://nl.wikipedia.org/wiki/Markdown">deze pagina</a> voor een beknopt overzicht van de opmaakmogelijkheden in markdown.
    </p>
    <p>
        Gebruik <code>ctrl-S</code> om wijzigingen op te slaan!
    </p>
    <p>Het is mogelijk om geselecteerde berichten te exporteren naar <code>xml</code> zodat deze in OSIRIS kunnen worden ingelezen. Daarnaast is het mogelijk om geselecteerde berichten in een booklet op te slaan.</p>
    <h4>Model</h4>
    <img src="{{ url_for('static', filename='flowchart.svg') }}" alt="flowchart">
</div>
<div class="collapsible">&#9664;</div>

<div class="rightpane">
    <h3>Navigatie</h3>
    <div class="appmap">
        <a href="{{ url_for('parameters.manage') }}" class="button appmap--item">Parameters</a>
        <div class="appmap--item">
            <div class="appmap--name">Parameters</div>
            <ul>
                <li>Variabele velden.</li>
                <li>Bruikbaar in snippets, layouts en messages.</li>
                <li>Verwijs met <code>$label</code> naar parameters.</li>
            </ul>
        </div>
        <a href="{{ url_for('snippets.manage') }}" class="button appmap--item">Snippets</a>
        <div class="appmap--item">
            <div class="appmap--name">Snippets</div>
            <ul>
                <li>Herbruikbare blokteksten.</li>
                <li>Bruikbaar in layouts en messages.</li>
                <li>Mogen parameters bevatten.</li>
                <li>Verwijs met <code>$label</code> naar snippets.</li>
            </ul>
        </div>
        <a href="{{ url_for('layouts.manage') }}" class="button appmap--item">Layouts</a>
        <div class="appmap--item">
            <div class="appmap--name">Layouts</div>
            <ul>
                <li>Opmaak van messages in html.</li>
                <li>Mogen parameters en snippets bevatten.</li>
                <li>Gebruik <code>$content</code> voor locatie message-tekst.</li>
            </ul>
        </div>
        <a href="{{ url_for('settings.manage') }}" class="button appmap--item">Settings</a>
        <div class="appmap--item">
            <div class="appmap--name">Settings</div>
            <ul>
                <li>Instellingen van het bericht.</li>
            </ul>
        </div>
        <a href="{{ url_for('messages.manage') }}" class="button appmap--item">Messages</a>
        <div class="appmap--item">
            <div class="appmap--name">Messages</div>
            <ul>
                <li>Tekstuele inhoud in markdown.</li>
                <li>Mogen parameters en snippets bevatten.</li>
                <li>Gekoppeld aan layout.</li>
            </ul>
        </div>
    </div>
</div>

{% endblock content %}